name: Test
on: push
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            
            - name: Use node.js
              uses: actions/setup-node@v3
              with:
                node-version: '>=22.x'

            
            - name: Installa dipendenze
              run: npm install

            - name: Aggiungi permessi esecuzione jest
              run: chmod +x ./node_modules/.bin/jest

            - name: Esegui i test con code coverage
              run: npm test

            - name: Carica i risultati della code coverage
              uses: actions/upload-artifact@v4
              with:
                name: coverage-report
                path: coverage