name: Test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            
            - name: Use nodejs
              uses: actions/setup-node@v3
              with:
                node-version: '>=14.x'

            - run: npm install
            - run: npm test